<a href="https://colab.research.google.com/github/GENTLEW1ND/Python/blob/main/Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Numpy Library : Numpy stands for Numerical Python.

In [1]:
import numpy as np

Matrix Addition

Two matrices can be added only if they have the same shape.

In [2]:
# Creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [3]:
# Creating two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))
sum = np.add(matrix_1, matrix_2)
print(sum)

[[18 14 19]
 [20 23 23]
 [23  9 12]]


Matrix Substraction

In [4]:
# Creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])
diff = A-B
print(diff)

[[-4 -4]
 [-4 -4]]


In [5]:
# Creating two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[ -7 -10 -15]
 [ -3  -2 -10]
 [  3  -2 -13]]


Matrix Multiplicaition uisng Scaler

In [6]:
x=5
y=np.array([[1,2],[3,4]])
mul = x*y
print(mul)

[[ 5 10]
 [15 20]]


Multiplication of two Matrices

In [7]:
# Creating two matrices
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])
mull = A * B
print(mull)

[[12 21]
 [32 45]]


In [8]:
# Creating two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))
mull = np.multiply(matrix_1, matrix_2)
print(mull)

[[ 32  40 144]
 [ 12  34  35]
 [126   0  24]]
