<a href="https://colab.research.google.com/github/GENTLEW1ND/Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Nummerical Python

Advantages of Numpy Arrays
  1. Allows several Mathematical Operations
  2. Faster operation

In [5]:
import numpy as np

List vs Numpy - Time taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0012069800000000797


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00013329799999972636


Numpy array

In [9]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [10]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

ndarray represents N Dimentions Array

In [11]:
#creating a 1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [12]:
a.shape

(4,)

(4,) represents 4 columns as its one dimentional.

In [14]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

(2,4) 2=> rows and 4=> columns

In [16]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [17]:
# create a numpy array of 0s

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# create a numpy array of 1s
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
# Create an Indentity Matrix
u = np.eye(4)
print(u)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# create a numpy array with random values
v = np.random.random([3,4])
print(v)
# all the values will be from 0 and 1

[[0.1662529  0.64766064 0.91797534 0.56905106]
 [0.07742453 0.36432818 0.03233177 0.80284335]
 [0.42773517 0.75650544 0.96432069 0.79924908]]


In [23]:
# random integer values array within a specific range
w = np.random.randint(10,100,[3,5])
print(w)

[[99 53 85 33 92]
 [12 58 89 65 45]
 [14 10 18 96 31]]


In [30]:
# create an array with evenly spaced values --> specifying the number of values required
q = np.linspace(10,30,5)
print(q)

[10. 15. 20. 25. 30.]


In [29]:
# array of evenly spaced values --> specifying the jump
s = np.arange(10,30,5)
print(s)

[10 15 20 25]


In [32]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [33]:
i = np.random.randint(10,90,(5,5))
print(i)

[[66 44 89 72 12]
 [53 19 64 70 83]
 [72 38 47 16 72]
 [83 64 76 15 20]
 [56 62 48 31 38]]


In [35]:
#array dimension
print(i.shape)

(5, 5)


In [36]:
# number of dimention
print(c.ndim)

2


In [37]:
# checking the number of elements in an array
print(i.size)

25


In [38]:
# checking the datatype of values in an array
print(i.dtype)

int64


Mathematical operations on a nparray.

In [39]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)  #it concatinate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np