<a href="https://colab.research.google.com/github/GENTLEW1ND/Python/blob/main/Working_with_Martix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Martix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,19]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 19]]


In [6]:
matrix_2.shape

(3, 3)

Creating matrices with random values.

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.85052464 0.29307808 0.83735968]
 [0.45153975 0.94481541 0.82772944]
 [0.2882742  0.17298613 0.86040785]]


In [8]:
# Creating matrix with random integers
random_integer_matrix = np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[97 30 63 63 66]
 [84 67 97 14 98]
 [85 76 26 91 22]
 [26 14 63  9 12]]


Matrix with all the values as 1

In [10]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
matrix_4 = np.ones((10,10), dtype=int)
print(matrix_4)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [13]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Creating an Identity Matrix

In [15]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of a Matrix

In [16]:
# matrix with random integer values
a = np.random.randint(100,size=(4,5))
print(a)

[[98 86 96  8  0]
 [ 1 86 44  1 86]
 [12 58 12 81 56]
 [48 12 91 88 18]]


In [17]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[98  1 12 48]
 [86 86 58 12]
 [96 44 12 91]
 [ 8  1 81 88]
 [ 0 86 56 18]]
